FROM ubuntu

RUN apt-get update && apt-get install -y curl

RUN curl -fsSL "https://github.com/CyberVy/netcraft/raw/refs/heads/main/netcraft/ray/ray_install.sh" | bash

CMD ./ray_assets/ray run -c ./ray_assets/config.json
