FROM ubuntu

RUN apt-get update && apt-get install -y curl

RUN curl -fsSL "https://github.com/CyberVy/netcraft/raw/refs/heads/main/netcraft/ray/ray_install.sh" | bash

CMD curl -Lo ./config.json "https://github.com/CyberVy/netcraft/raw/refs/heads/main/netcraft/ray/config.json" && \
    ./ray_assets/ray run -c ./config.json
