FROM ubuntu

RUN apt-get update && apt-get install -y curl
RUN curl -fsSL "https://github.com/CyberVy/netcraft/raw/refs/heads/main/netcraft/ray/ray_ui_install.sh" | bash && \
  ./ray_ui_assets/ray-ui setting -username admin -password admin -port 2053 -webBasePath /

CMD cd ./ray_ui_assets && ./ray-ui run
