name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build the ray image
      run: docker build -f netcraft/ray/Dockerfile_CORE -t ghcr.io/cybervy/netcraft/ray:latest netcraft/ray
    
    - name: Push the ray image
      run: docker push ghcr.io/cybervy/netcraft/ray:latest
