name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the ray image
      run: docker build -f netcraft/ray/Dockerfile_CORE -t ghcr.io/cybervy/ray:latest netcraft/ray
    
    - name: Push the ray image
      run: docker push ghcr.io/cybervy/ray:latest
