name: Ray Image CI

on:
  push:
    branches: [ "main" ]
    paths: 
     - 'netcraft/ray/**'
     - '.github/workflows/ray_docker.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'netcraft/ray/**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build the ray image
      run: docker build -f netcraft/ray/Dockerfile_CORE -t ghcr.io/$(echo "${{ github.repository_owner }}" | tr A-Z a-z)/netcraft:ray netcraft/ray
    
    - name: Push the ray image
      run: docker push ghcr.io/cybervy/netcraft

    # - name: Build the ray-ui image
    #   run: docker build -f netcraft/ray/Dockerfile_UI -t ghcr.io/$(echo "${{ github.repository_owner }}" | tr A-Z a-z)/netcraft:ray-ui netcraft/ray
    
    # - name: Push the ray-ui image
    #   run: docker push ghcr.io/cybervy/netcraft:ray-ui
