name: SSH Image CI

on:
  push:
    branches: [ "main" ]
    paths: 
     - 'netcraft/ssh/**'
     - '.github/workflows/ssh_docker.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'netcraft/ssh/**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}
        
    - name: Build the SSH image
      run: docker build -f netcraft/ssh/Dockerfile -t ghcr.io/$(echo "${{ github.repository_owner }}" | tr A-Z a-z)/ssh:latest netcraft/ssh
    
    - name: Push the SSH image
      run: docker push ghcr.io/cybervy/ssh:latest
